spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-LAAE5CE:1433;databaseName=HOSPITAL2_DB;encrypt=true;trustServerCertificate=true;
    username: sa
    password: htet
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true